disabled_rules:
- anyobject_protocol
- array_init
- closure_end_indentation
- conditional_returns_on_newline
- cyclomatic_complexity
- discouraged_optional_boolean
- discouraged_optional_collection
- empty_xctest_method
- file_header
- file_types_order
- force_cast
- fallthrough 
- identifier_name
- literal_expression_end_indentation
- missing_docs
- multiline_arguments_brackets
- multiline_parameters_brackets	
- nesting
- nimble_operator
- no_extension_access_modifier
- no_grouping_extension
- nslocalizedstring_require_bundle
- override_in_extension
- pattern_matching_keywords
- prohibited_interface_builder
- prohibited_super_call
- quick_discouraged_call
- quick_discouraged_focused_test
- quick_discouraged_pending_test
- redundant_optional_initialization
- redundant_type_annotation
- redundant_string_enum_value
- required_deinit
- required_enum_case
- single_test_class
- strict_fileprivate
- strong_iboutlet
- switch_case_on_newline 
- trailing_whitespace
- unavailable_function
- unneeded_parentheses_in_closure_argument
- untyped_error_in_catch

# length
- closure_body_length
- file_length
- function_body_length 
- function_parameter_count
- line_length
- type_body_length

# todo
- block_based_kvo
- function_default_parameter_at_end
- trailing_closure

# feature
- explicit_type_interface
- explicit_acl 
- explicit_top_level_acl 
- implicitly_unwrapped_optional
- type_contents_order
- type_name
- yoda_condition

opt_in_rules:
- attributes
- class_delegate_protocol
- closing_brace
- closure_spacing
- collection_alignment
- colon
- comma
- compiler_protocol_init
- contains_over_first_not_nil
- control_statement
- convenience_type
- deployment_target
- discarded_notification_center_observer
- discouraged_direct_init
- discouraged_object_literal
- duplicate_enum_cases
- duplicate_imports
- dynamic_inline
- empty_count
- empty_enum_arguments
- empty_parameters
- empty_parentheses_with_trailing_closure
- empty_string
- explicit_init
- extension_access_modifier
- fatal_error_message
# file_name
- first_where
- for_where
- force_try
- force_unwrapping
- generic_type_name
- identical_operands
- implicit_getter
# implicit_return
- inert_defer
- is_disjoint
- joined_default_parameter
- large_tuple
- last_where
- leading_whitespace
- legacy_cggeometry_functions
- legacy_constant
- legacy_constructor	
- legacy_hashing
- legacy_multiple
- legacy_nsgeometry_functions
- legacy_random
- let_var_whitespace
- lower_acl_than_parent
- mark
- modifier_order
- multiline_arguments
- multiline_function_chains
- multiline_literal_brackets
- multiline_parameters
- multiple_closures_with_trailing_closure
- no_fallthrough_only
- notification_center_detachment
- nslocalizedstring_key
- nsobject_prefer_isequal
- number_separator
- object_literal
- opening_brace
- operator_usage_whitespace
- operator_whitespace
- overridden_super_call
- prefixed_toplevel_constant
# private_action
# private_outlet
# private_over_fileprivate
- private_unit_test
- protocol_property_accessors_order	
- reduce_boolean
- reduce_into  
- redundant_discardable_let
- redundant_nil_coalescing
- redundant_objc_attribute
- redundant_set_access_control
- redundant_void_return
- return_arrow_whitespace
- shorthand_operator
- sorted_first_last
- sorted_imports
- statement_position
- static_operator
- switch_case_alignment
- syntactic_sugar
- todo
- toggle_bool
- trailing_comma
- trailing_newline
- trailing_semicolon
- unneeded_break_in_switch
# unowned_variable_capture
- unused_capture_list
- unused_closure_parameter
- unused_control_flow_label
- unused_enumerated
- unused_import
- unused_optional_binding
- unused_private_declaration
- unused_setter_value
- valid_ibinspectable
- vertical_parameter_alignment
- vertical_whitespace
# vertical_whitespace_between_cases
- vertical_whitespace_closing_braces
- vertical_whitespace_opening_braces
- void_return
- weak_delegate
- xct_specific_matcher
- xctfail_message

excluded:
- Build
- DerivedData
- Pods